
#line 3 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5
#define YY_FLEX_SUBMINOR_VERSION 35
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart(yyin  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    /* Note: We specifically omit the test for yy_rule_can_match_eol because it requires
     *       access to the local variable yy_act. Since yyless() is a macro, it would break
     *       existing scanners that call yyless() from OUTSIDE yylex. 
     *       One obvious solution it to make yy_act a global. I tried that, and saw
     *       a 5% performance hit in a non-yylineno scanner, because yy_act is
     *       normally declared as a register variable-- so it is not worth it.
     */
    #define  YY_LESS_LINENO(n) \
            do { \
                int yyl;\
                for ( yyl = n; yyl < yyleng; ++yyl )\
                    if ( yytext[yyl] == '\n' )\
                        --yylineno;\
            }while(0)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = 0; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart (FILE *input_file  );
void yy_switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer (FILE *file,int size  );
void yy_delete_buffer (YY_BUFFER_STATE b  );
void yy_flush_buffer (YY_BUFFER_STATE b  );
void yypush_buffer_state (YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state (void );

static void yyensure_buffer_stack (void );
static void yy_load_buffer_state (void );
static void yy_init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER yy_flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE yy_scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes (yyconst char *bytes,int len  );

void *yyalloc (yy_size_t  );
void *yyrealloc (void *,yy_size_t  );
void yyfree (void *  );

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define yywrap(n) 1
#define YY_SKIP_YYWRAP

typedef unsigned char YY_CHAR;

FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;

typedef int yy_state_type;

extern int yylineno;

int yylineno = 1;

extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
static void yy_fatal_error (yyconst char msg[]  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;

#define YY_NUM_RULES 99
#define YY_END_OF_BUFFER 100
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[352] =
    {   0,
        0,    0,   97,   97,    0,    0,  100,   95,   94,   93,
       91,   95,   81,   82,   36,   34,   85,   84,   43,   43,
       87,   83,   33,   86,   33,   39,   39,   39,   39,   39,
       39,   39,   39,   39,   39,   39,   39,   39,   39,   39,
       39,   39,   88,   89,   95,   95,   99,   97,   98,   42,
       41,   94,   93,   93,    0,    0,   43,    0,   50,    0,
       40,   73,    0,   40,   71,   71,    0,   90,   33,   39,
       39,   39,   39,    0,   39,   39,   39,   39,   39,   39,
       24,   39,   39,   39,   39,   39,   18,   38,   39,   39,
        6,   35,   39,   39,   39,   39,   39,   26,   39,   39,

       39,   39,   39,   39,    0,    0,    0,   92,   97,    0,
       74,    0,    0,    0,    0,    0,    0,   40,   51,   51,
       50,    0,    0,   62,   44,   44,    0,   73,   73,   66,
        0,   72,   46,   47,    0,   48,    0,   61,   36,   39,
       39,   39,   39,   39,   39,   39,   36,   39,   39,   17,
       39,   25,   39,   39,   36,   37,   39,   39,   39,   39,
        5,   39,   39,   39,    8,   39,   39,   39,   39,    0,
       96,   79,   76,   75,   78,   77,   80,   51,    0,    0,
       62,   49,   62,   62,   44,   45,   44,    0,    0,   53,
        0,   65,   68,   70,   72,   72,    0,   47,   47,   47,

        0,    0,   58,   60,   61,   61,   39,   39,   39,   21,
       15,   39,   39,   20,   39,   39,   39,   39,   39,   39,
       39,   29,   13,   39,   19,   31,    3,   39,   28,   39,
        0,    0,   64,   49,   62,   62,   49,   49,   44,    0,
       45,    0,   53,   52,   53,   53,   65,   65,   65,    0,
       67,    0,   69,   47,    0,    0,   58,   56,   58,   58,
       60,   60,    4,   16,   39,    2,   39,   32,   39,   39,
       39,   39,   39,   39,   39,   23,   30,    0,   63,   64,
       64,   49,   49,    0,   55,   52,   53,   53,   52,   52,
       65,   67,   67,   67,   69,   69,   69,    0,   59,   56,

       58,   58,   56,   56,   39,   27,   39,   39,   39,   39,
       39,   39,    7,    0,   63,   63,   54,   55,   55,   52,
       52,   67,   69,   57,   59,   59,   56,   56,   14,    9,
       39,   12,   39,   39,    1,    0,   54,   54,   57,   57,
       10,   39,   39,    0,   22,   11,    0,    0,    0,    0,
        0
    } ;

static yyconst flex_int32_t yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    4,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    5,    6,    7,    6,    6,    6,    6,    8,    9,
       10,   11,   12,   13,   14,   15,   16,   17,   18,   19,
       19,   19,   19,   19,   19,   19,   19,   20,   21,   22,
       23,   24,   25,    6,   26,   27,   28,   29,   30,   31,
       32,   33,   34,   35,   35,   36,   37,   38,   39,   40,
       35,   41,   42,   43,   44,   45,   46,   47,   48,   35,
       49,   50,   51,    6,   52,    6,   53,   54,   55,   56,

       57,   58,   59,   60,   61,   35,   35,   62,   63,   64,
       65,   66,   35,   67,   68,   69,   70,   71,   72,   73,
       74,   35,   75,   76,   77,    6,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst flex_int32_t yy_meta[78] =
    {   0,
        1,    1,    2,    3,    4,    5,    6,    7,    5,    5,
        5,    5,    7,    8,    9,    8,   10,   10,   10,    7,
        7,    7,    5,    7,    7,   11,   11,   11,   11,   11,
       11,   12,   12,   12,   12,   12,   12,   12,   12,   12,
       12,   12,   12,   12,   12,   12,   12,   12,    6,    8,
        8,   13,   11,   11,   11,   11,   11,   11,   12,   12,
       12,   12,   12,   12,   12,   12,   12,   12,   12,   12,
       12,   12,   12,   12,    6,    7,    6
    } ;

static yyconst flex_int16_t yy_base[379] =
    {   0,
        0,    0,   77,  154,   79,   80,  494, 1813,   83,   94,
     1813,  437, 1813, 1813, 1813,   83, 1813,   86,   74,   92,
      449, 1813,   89, 1813,  443,  112,  121,  148,  172,  176,
      183,  117,  227,  202,  232,  251,  255,  166,  258,  273,
      272,  290, 1813, 1813,    0,  111, 1813,    0,   68, 1813,
     1813,  257,  462,  356,  454,  354,  437,  106,  346,  316,
      349,  102,  127,  352,  371,  396,  327, 1813, 1813,  394,
      180,  412,  355,  393,  415,  418,  421,  425,  441,  463,
      467,  478,  473,  481,  504,  509,  238,  335,  523,  531,
      492,  518,  536,  541,  559,  546,  573,  549,  590,  599,

      602,  610,  605,  618,  614,  642,  351,  348,    0,  403,
     1813,  397,  394,  392,  390,  383,  372, 1813,  431,  658,
      663,  330,  127,  283,  437,  666,  457,  145,  154,  360,
      360,  160,  672,  680,  649,  683,  207,  686,  689,  699,
      304,  709,  712,  715,  736,  739,  761,  766,  775,  779,
      782,  791,  797,  803,  821,  827,  839,  848,  853,  867,
      875,  893,  899,  903,  906,  917,  921,  924,  930,  316,
     1813, 1813, 1813, 1813, 1813, 1813, 1813,  944,  757,  216,
      880,  947,  953,  966,  969,  972,  977,  869,  245,  986,
      310,  302,  300,  296,  293,  165,  991,  994,  997, 1000,

     1019,  262, 1003, 1022, 1025, 1028, 1031, 1042, 1045, 1048,
     1051, 1055, 1067, 1059, 1071, 1095, 1074, 1112, 1115, 1120,
     1134, 1140, 1143, 1161, 1151, 1166, 1170, 1179, 1187, 1193,
      283,  268, 1123, 1197, 1202, 1207, 1215, 1223, 1229, 1237,
     1235,  365, 1243, 1249, 1252, 1255,  278,  276,  272,  266,
      261,  235,  230, 1258, 1266,  375, 1264, 1272, 1276, 1279,
     1282, 1285, 1288, 1291, 1294, 1299, 1305, 1308, 1311, 1314,
     1319, 1336, 1350, 1366, 1372, 1355, 1377,  234, 1380, 1386,
     1392, 1395, 1398,  398, 1403, 1408, 1413, 1416, 1419, 1422,
      222,  213,  198,  193,  190,  185,  175,  401, 1425, 1428,

     1431, 1434, 1437, 1440, 1443, 1446, 1449, 1452, 1456, 1466,
     1469, 1492, 1497,  137, 1475, 1507, 1513, 1516, 1519, 1523,
     1528,  131,  124, 1533, 1539, 1542, 1545, 1548, 1551, 1554,
     1557, 1560, 1563, 1566, 1570,  124, 1573, 1579, 1582, 1606,
     1609, 1617, 1620,  109, 1623, 1626,  115,  106,  215,   39,
     1813, 1678, 1691, 1704, 1713, 1717, 1720, 1731, 1741, 1746,
     1748, 1752, 1756, 1760, 1763, 1765, 1767, 1769, 1771, 1774,
     1776, 1778, 1780, 1782, 1784, 1786, 1788, 1799
    } ;

static yyconst flex_int16_t yy_def[379] =
    {   0,
      351,    1,  352,  352,  353,  353,  351,  351,  351,  354,
      351,  355,  351,  351,  351,  351,  351,  351,  351,  351,
      351,  351,  351,  351,  351,  356,  356,  356,  356,  356,
       28,  356,  356,  356,  356,  356,  356,  356,  356,   28,
       28,   28,  351,  351,  357,  358,  351,  359,  351,  351,
      351,  351,  354,  354,  351,  351,  351,  351,  351,  351,
      351,  351,  360,  351,  351,  351,  351,  351,  351,  361,
      356,  356,  356,  362,  356,  356,  356,  356,  356,  356,
      356,  356,  356,  356,  356,  356,  356,  356,  356,  356,
      356,  356,  356,  356,  356,  356,  356,  356,  356,  356,

      356,  356,  356,  356,  363,  358,  351,  351,  359,  351,
      351,  351,  351,  351,  351,  351,  351,  351,  351,  351,
      351,  351,  351,  351,  351,  351,  351,  351,  351,  364,
      351,  365,  351,  351,  351,  351,  351,  351,  356,  356,
      362,  356,  356,  356,  356,  356,  356,  356,  356,  356,
      356,  356,  356,  356,  356,  356,  356,  356,  356,  356,
      356,  356,  356,  356,  356,  356,  356,  356,  363,  351,
      351,  351,  351,  351,  351,  351,  351,  351,  351,  351,
      351,  351,  351,  351,  351,  351,  351,  351,  351,  351,
      366,  367,  368,  369,  370,  365,  351,  351,  351,  351,

      351,  351,  351,  351,  351,  351,  356,  356,  356,  356,
      356,  356,  356,  356,  356,  356,  356,  356,  356,  356,
      356,  356,  356,  356,  356,  356,  356,  356,  356,  356,
      351,  351,  351,  351,  351,  351,  351,  351,  351,  351,
      351,  351,  351,  351,  351,  351,  371,  371,  367,  372,
      373,  374,  375,  351,  351,  351,  351,  351,  351,  351,
      351,  351,  356,  356,  356,  356,  356,  356,  356,  356,
      356,  356,  356,  356,  356,  356,  356,  351,  351,  351,
      351,  351,  351,  351,  351,  351,  351,  351,  351,  351,
      371,  376,  376,  373,  377,  377,  375,  351,  351,  351,

      351,  351,  351,  351,  356,  356,  356,  356,  356,  356,
      356,  356,  356,  351,  351,  351,  351,  351,  351,  351,
      351,  376,  377,  351,  351,  351,  351,  351,  356,  356,
      356,  356,  356,  356,  356,  351,  351,  351,  351,  351,
      356,  356,  356,  351,  356,  356,  378,  351,  351,  351,
        0,  351,  351,  351,  351,  351,  351,  351,  351,  351,
      351,  351,  351,  351,  351,  351,  351,  351,  351,  351,
      351,  351,  351,  351,  351,  351,  351,  351
    } ;

static yyconst flex_int16_t yy_nxt[1891] =
    {   0,
        8,    9,   10,    9,    9,    8,   11,   12,   13,   14,
       15,   16,   17,   16,   18,   15,   19,   20,   20,   21,
       22,   23,   24,   25,    8,   26,   27,   28,   29,   30,
       31,   32,   32,   33,   32,   32,   34,   35,   36,   37,
       38,   39,   40,   32,   41,   42,   32,   32,   43,    8,
       44,   45,   26,   27,   28,   29,   30,   31,   32,   32,
       33,   32,   34,   35,   36,   37,   38,   39,   40,   32,
       41,   42,   32,   32,   46,    8,    8,   47,   47,   47,
       47,   47,   47,   47,   52,   52,   52,   52,   61,  106,
       47,   62,   47,   51,   51,   54,   52,   54,   54,   57,

       57,   57,   58,   59,   59,  110,   64,  350,   65,   66,
       66,   69,   69,  106,  106,   60,  349,  106,  128,  129,
       63,   67,   58,  119,  119,   47,   49,   47,   70,   70,
       70,  110,  347,   70,   70,   70,  344,   70,   70,   70,
      296,  130,   60,  131,  182,  182,   63,  293,   67,   72,
       75,   47,   73,   47,   47,   47,   47,   47,  336,   76,
       47,  128,  128,   74,   70,   70,   70,   47,   74,   47,
      128,  129,   74,   77,  194,   72,  195,   75,   73,  194,
       78,  195,   70,   70,   70,   76,   79,  108,   70,   70,
       70,  296,   70,   70,   70,   95,   70,   70,   70,   74,

       77,  296,   47,   49,   47,   80,  296,   78,   84,  293,
       81,   82,   79,   83,  293,   71,  350,   74,   70,   70,
       70,   85,   95,   74,  204,  204,   86,   74,   47,  293,
       47,   74,   80,  234,  234,   84,   81,   82,  248,   83,
       89,  314,   71,   70,   70,   70,  296,   85,   70,   70,
       70,  252,   86,   74,   70,   70,   70,   87,   52,   52,
       52,   52,  244,  244,   88,  106,   89,   70,   70,   70,
       90,   70,   70,   70,   70,   70,   70,  293,   74,  258,
      258,   91,  250,   74,   87,  279,  279,   96,  248,   74,
       88,   92,  248,   93,  248,   94,   90,  101,   71,  183,

      184,  184,   74,  278,   71,   97,   74,  194,   91,   74,
       71,   98,  252,   99,   96,   71,  250,   92,  248,   93,
      100,   94,  102,  103,  101,   71,  191,  123,   71,  123,
      104,   71,   97,  124,  124,  231,   71,   98,  137,   99,
      137,  180,   71,  180,  138,  138,  100,  181,  181,  102,
      103,   70,   70,   70,   71,   74,  104,   54,   52,   54,
       54,  111,  120,  121,  121,  125,  126,  126,  133,  134,
      134,   70,   70,   70,  193,  122,  191,  154,  127,  177,
      112,  135,  286,  286,  113,  136,   74,   65,   65,   65,
      176,  114,  300,  300,  115,  140,  116,  175,  117,  174,

       67,  173,  122,  154,  172,  127,   74,  112,  135,  171,
      136,  113,   65,   66,   66,  317,  317,  114,  324,  324,
      115,  140,  116,  170,  117,   67,  170,   67,   70,   70,
       70,   70,   70,   70,   70,   70,   70,   70,   70,   70,
      139,   70,   70,   70,   74,   74,  142,  120,  178,  178,
      145,  118,   67,  125,  185,  185,  143,   70,   70,   70,
      179,  111,  144,   74,  351,   69,   74,  139,  189,   74,
      189,   68,   74,  142,  190,  190,   74,  145,  146,   70,
       70,   70,  143,   70,   70,   70,   56,  179,  144,   70,
       70,   70,   74,  351,   70,   70,   70,   70,   70,   70,

      351,  150,  351,  351,  146,  351,  351,  147,   70,   70,
       70,  351,  148,  351,   74,  351,  151,  351,   74,  149,
       70,   70,   70,  351,   74,   70,   70,   70,  150,   74,
      351,  351,   74,  147,   70,   70,   70,  351,  148,   70,
       70,   70,  151,   74,  152,  149,  153,   70,   70,   70,
      351,  155,   70,   70,   70,   74,  351,   70,   70,   70,
       74,  351,   70,   70,   70,   70,   70,   70,  157,   74,
      152,  351,  153,  156,   74,   70,   70,   70,  155,  158,
      351,  351,   74,  351,  159,  351,  160,   74,  161,   70,
       70,   70,   74,  351,  351,  157,  351,   74,  351,  156,

       74,  351,  162,  351,  351,  158,   70,   70,   70,  351,
       74,  159,  351,  160,  161,   70,   70,   70,   70,   70,
       70,   70,   70,   70,   74,  351,   70,   70,   70,  162,
      141,  141,  141,  163,   70,   70,   70,  351,  164,  351,
      351,   74,  165,  166,  106,  106,  351,  167,  106,  351,
       74,  168,  351,   74,  351,  351,   74,  351,  351,  163,
      202,   74,  202,  351,  164,   74,  203,  203,  165,   74,
      166,  351,  351,  167,  120,  178,  178,  351,  168,  120,
      121,  121,  186,  187,  187,  351,  351,  179,  197,  198,
      198,  351,  122,  351,  351,  188,  199,  200,  200,  133,

      134,  134,  205,  206,  206,   70,   70,   70,  351,  201,
      351,  351,  135,  351,  179,   70,   70,   70,  108,  122,
      351,  351,  188,  351,  207,   70,   70,   70,   70,   70,
       70,   70,   70,   70,  351,  351,  201,  351,  351,  135,
       74,  351,  208,  351,  210,  351,  351,  209,  351,  351,
       74,  207,   70,   70,   70,   70,   70,   70,  351,  351,
       74,  351,  351,   74,  351,  351,   74,  351,  232,  208,
      232,  210,  351,  209,  233,  233,  211,   70,   70,   70,
      212,  351,   70,   70,   70,  351,  351,   74,  351,  351,
       74,   70,   70,   70,  351,   70,   70,   70,   70,   70,

       70,  351,  211,  213,  214,  351,  212,   70,   70,   70,
      351,  351,   74,   70,   70,   70,  351,   74,  351,   70,
       70,   70,  351,  215,  217,  351,   74,  351,  351,  213,
       74,  214,  218,   74,  351,  351,  216,   70,   70,   70,
      351,  351,   74,   70,   70,   70,  351,  351,   74,  215,
      351,  217,  351,  351,   74,   70,   70,   70,  351,  218,
      351,  351,  216,  351,   70,   70,   70,  351,  219,   70,
       70,   70,   74,  351,  351,  220,  351,  351,   74,  221,
      242,  222,  242,   70,   70,   70,  243,  243,  223,  351,
       74,   70,   70,   70,  351,  219,  235,  236,  236,   74,

      351,  351,  220,  351,   74,  224,  221,  351,  222,   70,
       70,   70,  351,  351,  223,   70,   70,   70,   74,   70,
       70,   70,   70,   70,   70,  351,   74,  351,  226,  351,
      225,  224,  227,   70,   70,   70,  351,   70,   70,   70,
       70,   70,   70,  351,   74,  351,  141,  141,  141,  351,
       74,  351,  228,  229,   74,  226,  225,   74,  351,  227,
      120,  178,  178,  237,  238,  238,  230,  351,   74,  183,
      183,  183,   74,  179,  351,   74,  351,  351,  228,  351,
      229,   74,  183,  184,  184,  186,  239,  239,  186,  241,
      241,  351,  230,  186,  187,  187,  351,  351,  240,  351,

      179,  240,  245,  246,  246,  351,  188,  197,  198,  198,
      199,  254,  254,  199,  254,  254,  199,  200,  200,  259,
      260,  260,  351,  255,  351,  240,  255,  351,  240,  201,
      256,  351,  256,  188,  351,  351,  257,  257,  261,  262,
      262,  205,  205,  205,  205,  206,  206,   70,   70,   70,
      255,  351,  351,  255,  351,  351,  201,  351,   70,   70,
       70,   70,   70,   70,   70,   70,   70,   70,   70,   70,
      351,   70,   70,   70,  265,   70,   70,   70,  263,  264,
      351,  351,   74,   70,   70,   70,  351,   70,   70,   70,
       70,   70,   70,   74,  351,  351,   74,  266,  351,   74,

      268,  265,   74,  351,  263,  264,   74,  351,  351,  267,
       74,   70,   70,   70,  351,  351,  270,  351,   74,  351,
      269,  351,   74,  266,  351,   74,  351,  268,   70,   70,
       70,   70,   70,   70,  351,  267,   70,   70,   70,  280,
      281,  281,  270,  271,  351,  351,   74,  269,  351,  273,
       70,   70,   70,  351,  351,  272,   70,   70,   70,   70,
       70,   70,  351,   74,  351,  351,   74,   70,   70,   70,
      271,   74,  351,  351,  274,  351,  273,   70,   70,   70,
      351,  272,   70,   70,   70,   74,   70,   70,   70,  351,
      351,   74,  351,  351,   74,   70,   70,   70,  351,  351,

      274,  275,   74,   70,   70,   70,  351,  351,  276,   70,
       70,   70,   74,  282,  283,  283,  351,   74,  235,  235,
      235,   74,  277,  235,  236,  236,  351,  275,  351,  351,
       74,  237,  237,  237,  351,  276,  351,  351,   74,  237,
      238,  238,  351,  351,   74,  186,  239,  239,  284,  277,
      284,  186,  241,  241,  285,  285,  351,  351,  240,  287,
      288,  288,  351,  351,  240,  289,  290,  290,  245,  245,
      245,  245,  246,  246,  199,  254,  254,  298,  351,  298,
      301,  302,  302,  299,  299,  240,  351,  255,  303,  304,
      304,  240,  259,  259,  259,  259,  260,  260,  261,  261,

      261,  261,  262,  262,   70,   70,   70,   70,   70,   70,
       70,   70,   70,  351,  255,   70,   70,   70,  351,  305,
      351,   70,   70,   70,   70,   70,   70,   70,   70,   70,
       70,   70,   70,  351,  351,   70,   70,   70,  351,   74,
      351,  351,   74,  306,  351,   74,  305,  308,  309,  351,
       74,  307,   70,   70,   70,  351,   74,  351,  351,   74,
      351,  351,   74,  351,  351,   74,   70,   70,   70,  306,
       74,   70,   70,   70,  308,  309,  351,  307,  311,  351,
      351,  310,   70,   70,   70,  351,  351,   74,   70,   70,
       70,  312,  351,   70,   70,   70,  315,  316,  316,  351,

      313,   74,  280,  280,  280,  311,   74,  310,  280,  281,
      281,  282,  282,  282,  282,  283,  283,   74,  312,  318,
      319,  319,  351,   74,  320,  321,  321,  313,   74,  287,
      287,  287,  287,  288,  288,  289,  289,  289,  289,  290,
      290,  325,  326,  326,  327,  328,  328,  301,  301,  301,
      301,  302,  302,  303,  303,  303,  303,  304,  304,   70,
       70,   70,   70,   70,   70,   70,   70,   70,   70,   70,
       70,  351,   70,   70,   70,  351,  351,  330,  351,  351,
      329,  351,   70,   70,   70,   70,   70,   70,  351,  351,
      331,  315,  315,  315,   74,  351,  332,   74,  351,  333,

       74,  351,  351,   74,  330,  351,  329,   74,   70,   70,
       70,  351,  334,   70,   70,   70,  331,   74,  351,  351,
       74,  351,  332,  315,  316,  316,  333,  351,  335,  337,
      338,  338,  318,  318,  318,  318,  319,  319,  334,  320,
      320,  320,  351,   74,  320,  321,  321,  351,   74,  339,
      340,  340,  351,  351,  335,  325,  325,  325,  325,  326,
      326,  327,  327,  327,  327,  328,  328,   70,   70,   70,
       70,   70,   70,   70,   70,   70,   70,   70,   70,   70,
       70,   70,   70,   70,   70,  351,   70,   70,   70,  337,
      337,  337,  351,  351,  341,  337,  338,  338,  339,  339,

      339,  351,   74,  351,  342,   74,  343,  351,   74,  351,
      351,   74,  351,  351,   74,  351,  351,   74,  351,  351,
      341,   74,  339,  340,  340,   70,   70,   70,  351,  351,
      342,  351,  343,   70,   70,   70,   70,   70,   70,   70,
       70,   70,   70,   70,   70,  351,  345,  351,  351,  346,
      351,  351,  351,  351,  351,  351,  351,  351,  351,  351,
       74,  351,  351,  351,  351,  351,  351,  351,   74,  351,
      351,   74,  351,  345,   74,  351,  346,   74,   48,   48,
       48,   48,   48,   48,   48,   48,   48,   48,   48,   48,
       48,   50,   50,   50,   50,   50,   50,   50,   50,   50,

       50,   50,   50,   50,   53,   53,   53,   53,   53,   53,
       53,   53,   53,   53,   53,   53,   53,   55,   55,   55,
       55,   55,   55,   55,   55,   55,   71,   71,   71,   71,
      105,  105,  107,  107,  351,  107,  107,  351,  351,  351,
      107,  107,  107,  107,  109,  109,  351,  109,  351,  109,
      109,  109,  109,  109,  132,  132,  132,   70,   70,   70,
       70,  141,  141,  141,  141,  169,  169,  169,  169,  192,
      192,  196,  196,  196,  247,  247,  249,  249,  251,  251,
      253,  253,  195,  195,  195,  291,  291,  292,  292,  294,
      294,  295,  295,  297,  297,  322,  322,  323,  323,  348,

      351,  348,  348,  348,  348,  348,  348,  348,  348,  348,
      348,  348,    7,  351,  351,  351,  351,  351,  351,  351,
      351,  351,  351,  351,  351,  351,  351,  351,  351,  351,
      351,  351,  351,  351,  351,  351,  351,  351,  351,  351,
      351,  351,  351,  351,  351,  351,  351,  351,  351,  351,
      351,  351,  351,  351,  351,  351,  351,  351,  351,  351,
      351,  351,  351,  351,  351,  351,  351,  351,  351,  351,
      351,  351,  351,  351,  351,  351,  351,  351,  351,  351,
      351,  351,  351,  351,  351,  351,  351,  351,  351,  351
    } ;

static yyconst flex_int16_t yy_chk[1891] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    3,    3,    3,
        3,    5,    6,    3,    9,    9,    9,    9,   19,  350,
        3,   19,    3,    5,    6,   10,   10,   10,   10,   16,

       16,   16,   18,   18,   18,   49,   20,  348,   20,   20,
       20,   23,   23,   46,   46,   18,  347,   46,   62,   62,
       19,   20,   58,   58,   58,    3,    3,    3,   26,   26,
       26,   49,  344,   32,   32,   32,  336,   27,   27,   27,
      323,   63,   18,   63,  123,  123,   19,  322,   20,   26,
       27,    3,   26,    3,    4,    4,    4,    4,  314,   27,
        4,  128,  128,   26,   28,   28,   28,    4,   32,    4,
      129,  129,   27,   28,  132,   26,  132,   27,   26,  196,
       28,  196,   38,   38,   38,   27,   28,   46,   29,   29,
       29,  297,   30,   30,   30,   38,   71,   71,   71,   28,

       28,  296,    4,    4,    4,   29,  295,   28,   31,  294,
       29,   30,   28,   30,  293,   31,  349,   38,   34,   34,
       34,   31,   38,   29,  137,  137,   31,   30,    4,  292,
        4,   71,   29,  180,  180,   31,   29,   30,  291,   30,
       34,  278,   31,   33,   33,   33,  253,   31,   35,   35,
       35,  252,   31,   34,   87,   87,   87,   33,   52,   52,
       52,   52,  189,  189,   33,  349,   34,   36,   36,   36,
       35,   37,   37,   37,   39,   39,   39,  251,   33,  202,
      202,   36,  250,   35,   33,  232,  232,   39,  249,   87,
       33,   36,  248,   36,  247,   37,   35,   41,   40,  124,

      124,  124,   36,  231,   41,   40,   37,  195,   36,   39,
       41,   40,  194,   40,   39,   42,  193,   36,  192,   36,
       40,   37,   42,   42,   41,   40,  191,   60,   42,   60,
       42,   41,   40,   60,   60,  170,   41,   40,   67,   40,
       67,  122,   42,  122,   67,   67,   40,  122,  122,   42,
       42,   88,   88,   88,   42,  141,   42,   54,   54,   54,
       54,   56,   59,   59,   59,   61,   61,   61,   64,   64,
       64,   73,   73,   73,  131,   59,  130,   88,   61,  117,
       56,   64,  242,  242,   56,   65,   88,   65,   65,   65,
      116,   56,  256,  256,   56,   73,   56,  115,   56,  114,

       65,  113,   59,   88,  112,   61,   73,   56,   64,  110,
       66,   56,   66,   66,   66,  284,  284,   56,  298,  298,
       56,   73,   56,  108,   56,   66,  107,   65,   72,   72,
       72,   75,   75,   75,   76,   76,   76,   77,   77,   77,
       72,   78,   78,   78,   74,   70,   75,  119,  119,  119,
       78,   57,   66,  125,  125,  125,   76,   79,   79,   79,
      119,   55,   77,   72,   53,   25,   75,   72,  127,   76,
      127,   21,   77,   75,  127,  127,   78,   78,   79,   80,
       80,   80,   76,   81,   81,   81,   12,  119,   77,   83,
       83,   83,   79,    7,   82,   82,   82,   84,   84,   84,

        0,   83,    0,    0,   79,    0,    0,   80,   91,   91,
       91,    0,   81,    0,   80,    0,   84,    0,   81,   82,
       85,   85,   85,    0,   83,   86,   86,   86,   83,   82,
        0,    0,   84,   80,   92,   92,   92,    0,   81,   89,
       89,   89,   84,   91,   85,   82,   86,   90,   90,   90,
        0,   89,   93,   93,   93,   85,    0,   94,   94,   94,
       86,    0,   96,   96,   96,   98,   98,   98,   93,   92,
       85,    0,   86,   90,   89,   95,   95,   95,   89,   94,
        0,    0,   90,    0,   95,    0,   95,   93,   96,   97,
       97,   97,   94,    0,    0,   93,    0,   96,    0,   90,

       98,    0,   97,    0,    0,   94,   99,   99,   99,    0,
       95,   95,    0,   95,   96,  100,  100,  100,  101,  101,
      101,  103,  103,  103,   97,    0,  102,  102,  102,   97,
      105,  105,  105,   99,  104,  104,  104,    0,  100,    0,
        0,   99,  101,  102,  106,  106,    0,  103,  106,    0,
      100,  104,    0,  101,    0,    0,  103,    0,    0,   99,
      135,  102,  135,    0,  100,  105,  135,  135,  101,  104,
      102,    0,    0,  103,  120,  120,  120,    0,  104,  121,
      121,  121,  126,  126,  126,    0,    0,  120,  133,  133,
      133,    0,  121,    0,    0,  126,  134,  134,  134,  136,

      136,  136,  138,  138,  138,  139,  139,  139,    0,  134,
        0,    0,  136,    0,  120,  140,  140,  140,  106,  121,
        0,    0,  126,    0,  140,  142,  142,  142,  143,  143,
      143,  144,  144,  144,    0,    0,  134,    0,    0,  136,
      139,    0,  142,    0,  144,    0,    0,  143,    0,    0,
      140,  140,  145,  145,  145,  146,  146,  146,    0,    0,
      142,    0,    0,  143,    0,    0,  144,    0,  179,  142,
      179,  144,    0,  143,  179,  179,  145,  147,  147,  147,
      146,    0,  148,  148,  148,    0,    0,  145,    0,    0,
      146,  149,  149,  149,    0,  150,  150,  150,  151,  151,

      151,    0,  145,  148,  149,    0,  146,  152,  152,  152,
        0,    0,  147,  153,  153,  153,    0,  148,    0,  154,
      154,  154,    0,  151,  153,    0,  149,    0,    0,  148,
      150,  149,  154,  151,    0,    0,  152,  155,  155,  155,
        0,    0,  152,  156,  156,  156,    0,    0,  153,  151,
        0,  153,    0,    0,  154,  157,  157,  157,    0,  154,
        0,    0,  152,    0,  158,  158,  158,    0,  157,  159,
      159,  159,  155,    0,    0,  158,    0,    0,  156,  158,
      188,  159,  188,  160,  160,  160,  188,  188,  159,    0,
      157,  161,  161,  161,    0,  157,  181,  181,  181,  158,

        0,    0,  158,    0,  159,  160,  158,    0,  159,  162,
      162,  162,    0,    0,  159,  163,  163,  163,  160,  164,
      164,  164,  165,  165,  165,    0,  161,    0,  163,    0,
      162,  160,  164,  166,  166,  166,    0,  167,  167,  167,
      168,  168,  168,    0,  162,    0,  169,  169,  169,    0,
      163,    0,  166,  167,  164,  163,  162,  165,    0,  164,
      178,  178,  178,  182,  182,  182,  168,    0,  166,  183,
      183,  183,  167,  178,    0,  168,    0,    0,  166,    0,
      167,  169,  184,  184,  184,  185,  185,  185,  186,  186,
      186,    0,  168,  187,  187,  187,    0,    0,  185,    0,

      178,  186,  190,  190,  190,    0,  187,  197,  197,  197,
      198,  198,  198,  199,  199,  199,  200,  200,  200,  203,
      203,  203,    0,  198,    0,  185,  199,    0,  186,  200,
      201,    0,  201,  187,    0,    0,  201,  201,  204,  204,
      204,  205,  205,  205,  206,  206,  206,  207,  207,  207,
      198,    0,    0,  199,    0,    0,  200,    0,  208,  208,
      208,  209,  209,  209,  210,  210,  210,  211,  211,  211,
        0,  212,  212,  212,  209,  214,  214,  214,  207,  208,
        0,    0,  207,  213,  213,  213,    0,  215,  215,  215,
      217,  217,  217,  208,    0,    0,  209,  212,    0,  210,

      215,  209,  211,    0,  207,  208,  212,    0,    0,  213,
      214,  216,  216,  216,    0,    0,  217,    0,  213,    0,
      216,    0,  215,  212,    0,  217,    0,  215,  218,  218,
      218,  219,  219,  219,    0,  213,  220,  220,  220,  233,
      233,  233,  217,  218,    0,    0,  216,  216,    0,  220,
      221,  221,  221,    0,    0,  219,  222,  222,  222,  223,
      223,  223,    0,  218,    0,    0,  219,  225,  225,  225,
      218,  220,    0,    0,  221,    0,  220,  224,  224,  224,
        0,  219,  226,  226,  226,  221,  227,  227,  227,    0,
        0,  222,    0,    0,  223,  228,  228,  228,    0,    0,

      221,  224,  225,  229,  229,  229,    0,    0,  228,  230,
      230,  230,  224,  234,  234,  234,    0,  226,  235,  235,
      235,  227,  230,  236,  236,  236,    0,  224,    0,    0,
      228,  237,  237,  237,    0,  228,    0,    0,  229,  238,
      238,  238,    0,    0,  230,  239,  239,  239,  240,  230,
      240,  241,  241,  241,  240,  240,    0,    0,  239,  243,
      243,  243,    0,    0,  241,  244,  244,  244,  245,  245,
      245,  246,  246,  246,  254,  254,  254,  255,    0,  255,
      257,  257,  257,  255,  255,  239,    0,  254,  258,  258,
      258,  241,  259,  259,  259,  260,  260,  260,  261,  261,

      261,  262,  262,  262,  263,  263,  263,  264,  264,  264,
      265,  265,  265,    0,  254,  266,  266,  266,    0,  265,
        0,  267,  267,  267,  268,  268,  268,  269,  269,  269,
      270,  270,  270,    0,    0,  271,  271,  271,    0,  263,
        0,    0,  264,  267,    0,  265,  265,  270,  271,    0,
      266,  269,  272,  272,  272,    0,  267,    0,    0,  268,
        0,    0,  269,    0,    0,  270,  273,  273,  273,  267,
      271,  276,  276,  276,  270,  271,    0,  269,  273,    0,
        0,  272,  274,  274,  274,    0,    0,  272,  275,  275,
      275,  274,    0,  277,  277,  277,  279,  279,  279,    0,

      275,  273,  280,  280,  280,  273,  276,  272,  281,  281,
      281,  282,  282,  282,  283,  283,  283,  274,  274,  285,
      285,  285,    0,  275,  286,  286,  286,  275,  277,  287,
      287,  287,  288,  288,  288,  289,  289,  289,  290,  290,
      290,  299,  299,  299,  300,  300,  300,  301,  301,  301,
      302,  302,  302,  303,  303,  303,  304,  304,  304,  305,
      305,  305,  306,  306,  306,  307,  307,  307,  308,  308,
      308,    0,  309,  309,  309,    0,    0,  307,    0,    0,
      305,    0,  310,  310,  310,  311,  311,  311,    0,    0,
      308,  315,  315,  315,  305,    0,  309,  306,    0,  310,

      307,    0,    0,  308,  307,    0,  305,  309,  312,  312,
      312,    0,  311,  313,  313,  313,  308,  310,    0,    0,
      311,    0,  309,  316,  316,  316,  310,    0,  312,  317,
      317,  317,  318,  318,  318,  319,  319,  319,  311,  320,
      320,  320,    0,  312,  321,  321,  321,    0,  313,  324,
      324,  324,    0,    0,  312,  325,  325,  325,  326,  326,
      326,  327,  327,  327,  328,  328,  328,  329,  329,  329,
      330,  330,  330,  331,  331,  331,  332,  332,  332,  333,
      333,  333,  334,  334,  334,    0,  335,  335,  335,  337,
      337,  337,    0,    0,  331,  338,  338,  338,  339,  339,

      339,    0,  329,    0,  333,  330,  334,    0,  331,    0,
        0,  332,    0,    0,  333,    0,    0,  334,    0,    0,
      331,  335,  340,  340,  340,  341,  341,  341,    0,    0,
      333,    0,  334,  342,  342,  342,  343,  343,  343,  345,
      345,  345,  346,  346,  346,    0,  342,    0,    0,  343,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
      341,    0,    0,    0,    0,    0,    0,    0,  342,    0,
        0,  343,    0,  342,  345,    0,  343,  346,  352,  352,
      352,  352,  352,  352,  352,  352,  352,  352,  352,  352,
      352,  353,  353,  353,  353,  353,  353,  353,  353,  353,

      353,  353,  353,  353,  354,  354,  354,  354,  354,  354,
      354,  354,  354,  354,  354,  354,  354,  355,  355,  355,
      355,  355,  355,  355,  355,  355,  356,  356,  356,  356,
      357,  357,  358,  358,    0,  358,  358,    0,    0,    0,
      358,  358,  358,  358,  359,  359,    0,  359,    0,  359,
      359,  359,  359,  359,  360,  360,  360,  361,  361,  361,
      361,  362,  362,  362,  362,  363,  363,  363,  363,  364,
      364,  365,  365,  365,  366,  366,  367,  367,  368,  368,
      369,  369,  370,  370,  370,  371,  371,  372,  372,  373,
      373,  374,  374,  375,  375,  376,  376,  377,  377,  378,

        0,  378,  378,  378,  378,  378,  378,  378,  378,  378,
      378,  378,  351,  351,  351,  351,  351,  351,  351,  351,
      351,  351,  351,  351,  351,  351,  351,  351,  351,  351,
      351,  351,  351,  351,  351,  351,  351,  351,  351,  351,
      351,  351,  351,  351,  351,  351,  351,  351,  351,  351,
      351,  351,  351,  351,  351,  351,  351,  351,  351,  351,
      351,  351,  351,  351,  351,  351,  351,  351,  351,  351,
      351,  351,  351,  351,  351,  351,  351,  351,  351,  351,
      351,  351,  351,  351,  351,  351,  351,  351,  351,  351
    } ;

/* Table of booleans, true if rule could match eol. */
static yyconst flex_int32_t yy_rule_can_match_eol[100] =
    {   0,
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 
        };

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "new2.lex"


#line 9 "new2.lex"

#include <stdio.h>
#include <string.h>
#include <ctype.h>



#define ID		1
#define ICONST		2
#define RCONST		3
#define BCONST		4
#define CCONST		5
#define STRING		6

 /* reserver symbols */
#define PROGRAM		7
#define CONST		8
#define TYPE		9
#define ARRAY		10
#define SET		11
#define OF		12
#define RECORD		13
#define VAR		14
#define FORWARD		15
#define FUNCTION	16
#define PROCEDURE	17
#define INTEGER		18
#define REAL		19
#define BOOLEAN		20
#define CHAR		21
#define BEGIN2		22
#define END		23
#define IF		24
#define THEN		25
#define ELSE		26
#define CASE		27
#define OTHERWISE	28
#define WHILE		29
#define DO		30
#define FOR		31
#define TO		32
#define DOWNTO		33
#define WITH		34
#define READ		35
#define WRITE		36

 /* operators */
#define RELOP		37
#define ADDOP		38
#define OROP		39
#define MULDIVANDOP	40
#define NOTOP		41
#define INOP		42
#define LPAREN		43
#define RPAREN		44
#define SEMI		45
#define DOT		46
#define COMMA		47
#define EQU		48
#define COLON		49
#define LBRACK		50
#define RBRACK		51
#define ASSIGN		52
#define DOTDOT		53

void ERROR(const char *msg);
int checkSymbol(char *current);
int insertSymbol(char *current);


typedef struct{
	int intval;
	int intval2;
	char *strval;
	}YYSTYPE;
	
YYSTYPE yylval;
char *msg="Brethike lathos";
int sfalma=0;
int flag=0;
char array;
char *c,*b;
char linebuf[500];


struct SymbolTable {
  int index;
  char *content;
  struct SymbolTable *next;
};


#line 1116 "lex.yy.c"

#define INITIAL 0
#define str 1
#define teleia 2

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals (void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy (void );

int yyget_debug (void );

void yyset_debug (int debug_flag  );

YY_EXTRA_TYPE yyget_extra (void );

void yyset_extra (YY_EXTRA_TYPE user_defined  );

FILE *yyget_in (void );

void yyset_in  (FILE * in_str  );

FILE *yyget_out (void );

void yyset_out  (FILE * out_str  );

int yyget_leng (void );

char *yyget_text (void );

int yyget_lineno (void );

void yyset_lineno (int line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap (void );
#else
extern int yywrap (void );
#endif
#endif

    static void yyunput (int c,char *buf_ptr  );
    
#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, yyin))==0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;
    
#line 115 "new2.lex"





#line 1311 "lex.yy.c"

	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer(yyin,YY_BUF_SIZE );
		}

		yy_load_buffer_state( );
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 352 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 1813 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

		if ( yy_act != YY_END_OF_BUFFER && yy_rule_can_match_eol[yy_act] )
			{
			int yyl;
			for ( yyl = 0; yyl < yyleng; ++yyl )
				if ( yytext[yyl] == '\n' )
					   
    yylineno++;
;
			}

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 120 "new2.lex"
{printf("PROGRAM keyword\n"); return PROGRAM;}
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 121 "new2.lex"
{printf("CONST keyword\n"); return CONST;}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 122 "new2.lex"
{printf("TYPE keyword\n"); return TYPE;}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 123 "new2.lex"
{printf("ARRAY keyword\n"); return ARRAY;}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 124 "new2.lex"
{printf("SET keyword\n"); return SET;}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 125 "new2.lex"
{printf("OF keyword\n"); return OF;}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 126 "new2.lex"
{printf("RECORD keyword\n"); return RECORD;}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 127 "new2.lex"
{printf("VAR keyword\n"); return VAR;}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 128 "new2.lex"
{printf("FORWARD keyword\n"); return FORWARD;}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 129 "new2.lex"
{printf("FUNCTION keyword\n"); return FUNCTION;}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 130 "new2.lex"
{printf("PROCEDURE keyword\n"); return PROCEDURE;}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 131 "new2.lex"
{printf("INTEGER keyword\n");return INTEGER;}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 132 "new2.lex"
{printf("REAL keyword\n"); return REAL;}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 133 "new2.lex"
{printf("BOOLEAN keyword\n"); return BOOLEAN;}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 134 "new2.lex"
{printf("CHAR keyword\n"); return CHAR;}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 135 "new2.lex"
{printf("BEGIN keyword\n"); return BEGIN2;}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 136 "new2.lex"
{printf("END keyword\n"); return END;}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 137 "new2.lex"
{printf("IF keyword\n"); return IF;}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 138 "new2.lex"
{printf("THEN keyword\n"); return THEN;}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 139 "new2.lex"
{printf("ELSE keyword\n"); return ELSE;}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 140 "new2.lex"
{printf("CASE keyword\n"); return CASE;}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 141 "new2.lex"
{printf("OTHERWISE keyword\n"); return OTHERWISE;}
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 142 "new2.lex"
{printf("WHILE keyword\n"); return WHILE;}
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 143 "new2.lex"
{printf("DO keyword\n"); return  DO;}
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 144 "new2.lex"
{printf("FOR keyword\n"); return  FOR;}
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 145 "new2.lex"
{printf("TO keyword\n"); return  TO;}
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 146 "new2.lex"
{printf("DOWNTO keyword\n"); return DOWNTO;}
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 147 "new2.lex"
{printf("WITH keyword\n"); return WITH;}
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 148 "new2.lex"
{printf("READ keyword\n"); return READ;}
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 149 "new2.lex"
{printf("WRITE keyword\n"); return WRITE;}
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 151 "new2.lex"
{printf("BCONST: %s\n",yytext);yylval.intval=1;return BCONST;}
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 152 "new2.lex"
{printf("BCONST: %s\n",yytext);yylval.intval=0;return BCONST;}
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 154 "new2.lex"
{printf("RELOP: %s\n",yytext);return RELOP;}
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 155 "new2.lex"
{printf("ADDOP: %s\n",yytext);return ADDOP;}
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 156 "new2.lex"
{printf("OROP: %s\n",yytext);return OROP;}
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 157 "new2.lex"
{printf("MULDIVANDOP: %s\n",yytext);return MULDIVANDOP;}
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 158 "new2.lex"
{printf("NOTOP: %s\n",yytext);return NOTOP;}
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 159 "new2.lex"
{printf("IN: %s\n",yytext);return INOP;}
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 162 "new2.lex"
{printf("ID: %s\n",yytext); return ID;}
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 164 "new2.lex"
{printf("DOT: %s\n",yytext);BEGIN(teleia);return DOT;}
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 166 "new2.lex"
{printf("dotdot found\n");BEGIN(0);return DOTDOT;}
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 167 "new2.lex"
{array=(char) yytext;unput(array);BEGIN(0);}
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 170 "new2.lex"
{printf("Decimal ICONST: %s \n", yytext);yylval.intval=atoi(yytext);return ICONST;}
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 171 "new2.lex"
{printf("Decimal RCONST : %s \n", yytext);yylval.intval=atof(yytext);return RCONST;}
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 172 "new2.lex"
{printf("Decimal RCONST : %s \n", yytext);yylval.intval=atof(yytext);return RCONST;}
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 173 "new2.lex"
{printf("Decimal RCONST : %s \n", yytext);yylval.intval=atof(yytext);return RCONST;}
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 174 "new2.lex"
{printf("Decimal RCONST : %s \n", yytext);yylval.intval=atof(yytext);return RCONST;}
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 175 "new2.lex"
{printf("Decimal RCONST : %s \n", yytext);yylval.intval=atof(yytext);return RCONST;}
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 176 "new2.lex"
{printf("Decimal RCONST : %s \n", yytext);yylval.intval=atof(yytext);return RCONST;}
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 177 "new2.lex"
{printf("Decimal RCONST : %s \n", yytext);yylval.intval=atof(yytext);return RCONST;}
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 178 "new2.lex"
{printf("Decimal RCONST : %s \n", yytext);yylval.intval=atof(yytext);return RCONST;}
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 179 "new2.lex"
{printf("Decimal RCONST : %s \n", yytext);yylval.intval=atof(yytext);return RCONST;}
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 180 "new2.lex"
{printf("Decimal RCONST : %s \n", yytext);yylval.intval=atof(yytext);return RCONST;}
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 181 "new2.lex"
{printf("Decimal RCONST : %s \n", yytext);yylval.intval=atof(yytext);return RCONST;}
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 182 "new2.lex"
{printf("Decimal RCONST : %s \n", yytext);yylval.intval=atof(yytext);return RCONST;}
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 183 "new2.lex"
{printf("Decimal RCONST : %s \n", yytext);yylval.intval=atof(yytext);return RCONST;}
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 184 "new2.lex"
{printf("Decimal RCONST : %s \n", yytext);yylval.intval=atof(yytext);return RCONST;}
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 185 "new2.lex"
{printf("Decimal RCONST : %s \n", yytext);yylval.intval=atof(yytext);return RCONST;}
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 186 "new2.lex"
{printf("Decimal RCONST : %s \n", yytext);yylval.intval=atof(yytext);return RCONST;}
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 187 "new2.lex"
{printf("Decimal RCONST : %s \n", yytext);yylval.intval=atof(yytext);return RCONST;}
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 188 "new2.lex"
{printf("Decimal RCONST : %s \n", yytext);yylval.intval=atof(yytext);return RCONST;}
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 189 "new2.lex"
{printf("decimal RCONST : %s \n", yytext);yylval.intval=atof(yytext);return RCONST;}
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 190 "new2.lex"
{printf("Decimal RCONST : %s \n", yytext);yylval.intval=atof(yytext);return RCONST;}
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 191 "new2.lex"
{printf("Decimal RCONST : %s \n", yytext);yylval.intval=atof(yytext);return RCONST;}
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 192 "new2.lex"
{printf("hex RCONST : %s \n", yytext);yylval.intval=atof(yytext);return RCONST;}
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 193 "new2.lex"
{printf("hex RCONST : %s \n", yytext);yylval.intval=atof(yytext);return RCONST;}
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 194 "new2.lex"
{printf("hex RCONST : %s \n", yytext);yylval.intval=atof(yytext);return RCONST;}
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 195 "new2.lex"
{printf("hex RCONST : %s \n", yytext);yylval.intval=atof(yytext);return RCONST;}
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 196 "new2.lex"
{printf("hex RCONST : %s \n", yytext);yylval.intval=atof(yytext);return RCONST;}
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 197 "new2.lex"
{printf("hex RCONST : %s \n", yytext);yylval.intval=atof(yytext);return RCONST;}
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 200 "new2.lex"
{printf("Decimal ICONST: %s \n", yytext);yylval.intval=atoi(yytext);return ICONST;}
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 201 "new2.lex"
{printf("Hex ICONST:  %s \n",  yytext);yylval.intval=atof(yytext);return ICONST;}
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 202 "new2.lex"
{printf("Binary ICONST:  %s \n", yytext);yylval.intval=atof(yytext);return ICONST;}
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 206 "new2.lex"
{printf("Cconst : %s\n",yytext);yylval.strval=strdup(yytext);return CCONST;}
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 207 "new2.lex"
{printf("Cconst: Line feed\n");yylval.strval=yytext;return CCONST;}
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 208 "new2.lex"
{printf("Cconst: Form feed\n");yylval.strval=yytext;return CCONST;}
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 209 "new2.lex"
{printf("Cconst: Horizontal Tab\n");yylval.strval=yytext;return CCONST;}
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 210 "new2.lex"
{printf("Cconst: Carriage return\n");yylval.strval=yytext;return CCONST;}
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 211 "new2.lex"
{printf("Cconst: Back Space\n");yylval.strval=yytext;return CCONST;}
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 212 "new2.lex"
{printf("Cconst: Vertical Tab\n");yylval.strval=yytext;return CCONST;}
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 217 "new2.lex"
{printf("LPAREN: %s\n",yytext);return LPAREN;}
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 218 "new2.lex"
{printf("RPAREN: %s\n",yytext);return RPAREN;}
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 219 "new2.lex"
{printf("SEMI: %s\n",yytext);return SEMI;}
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 220 "new2.lex"
{printf("DOT: %s\n",yytext);BEGIN(teleia);return DOT;}
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 221 "new2.lex"
{printf("COMMA: %s\n",yytext);return COMMA;}
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 222 "new2.lex"
{printf("EQU: %s\n",yytext);return EQU;}
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 223 "new2.lex"
{printf("COLON: %s\n",yytext);return COLON;}
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 224 "new2.lex"
{printf("LBRACK: %s\n",yytext);return LBRACK;}
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 225 "new2.lex"
{printf("RBRACK: %s\n",yytext);return RBRACK;}
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 226 "new2.lex"
{printf("ASSIGN: %s\n",yytext);return ASSIGN;}
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 229 "new2.lex"
{
			  printf("String found : ");
			  BEGIN(str);
			}
	YY_BREAK
case 92:
/* rule 92 can match eol */
YY_RULE_SETUP
#line 233 "new2.lex"
{printf("Comment found: %s\n",yytext);}
	YY_BREAK
case 93:
/* rule 93 can match eol */
YY_RULE_SETUP
#line 235 "new2.lex"
{ strncpy(linebuf, yytext+1, sizeof(linebuf)); 
            yyless(1);     
          }
	YY_BREAK
case 94:
/* rule 94 can match eol */
YY_RULE_SETUP
#line 239 "new2.lex"
{}
	YY_BREAK
case 95:
YY_RULE_SETUP
#line 241 "new2.lex"
{
					if(sfalma==0){
					printf("Panic mode\n");
						sfalma=1;
					
					}
					else{
						ERROR(msg);
					}
				}
	YY_BREAK
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(str):
case YY_STATE_EOF(teleia):
#line 252 "new2.lex"
{printf("EOF\n"); return 0;}
	YY_BREAK
case 96:
YY_RULE_SETUP
#line 256 "new2.lex"
{yytext=c;
			  printf("End of string: %s\n",yytext);  
			  BEGIN(0);
			  return STRING;}
	YY_BREAK
case 97:
YY_RULE_SETUP
#line 261 "new2.lex"
{
					      printf("\nPart of string: %s\n",yytext);
					      if(flag==1){
						c=(char *)malloc(strlen(yytext)+strlen(b));
						if(c!=NULL){
						  strcpy(c,b);
						  strcat(c,yytext);
						 }
					      }
						else{
						  b=(char *)malloc(strlen(yytext)+1);
						  strcpy(b,yytext);
						}
					}
	YY_BREAK
case 98:
YY_RULE_SETUP
#line 275 "new2.lex"
{
				printf("Slash found : ");
				array=input();
				flag=1;
				while (array == ' ' || array == '\n' ){
				array=input();
				
				};
				unput(array);
				BEGIN(str);
			}
	YY_BREAK
case 99:
YY_RULE_SETUP
#line 289 "new2.lex"
ECHO;
	YY_BREAK
#line 1948 "lex.yy.c"

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	register char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	register char *source = (yytext_ptr);
	register int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc((void *) b->yy_ch_buf,b->yy_buf_size + 2  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), (size_t) num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart(yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((yy_size_t) ((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		yy_size_t new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	register yy_state_type yy_current_state;
	register char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 352 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	register int yy_is_jam;
    	register char *yy_cp = (yy_c_buf_p);

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 352 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 351);

	return yy_is_jam ? 0 : yy_current_state;
}

    static void yyunput (int c, register char * yy_bp )
{
	register char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = (yy_n_chars) + 2;
		register char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		register char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

    if ( c == '\n' ){
        --yylineno;
    }

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart(yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap( ) )
						return EOF;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	if ( c == '\n' )
		   
    yylineno++;
;

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer(yyin,YY_BUF_SIZE );
	}

	yy_init_buffer(YY_CURRENT_BUFFER,input_file );
	yy_load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree((void *) b->yy_ch_buf  );

	yyfree((void *) b  );
}

#ifndef __cplusplus
extern int isatty (int );
#endif /* __cplusplus */
    
/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	int num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );
								  
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		int grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (yyconst char * yystr )
{
    
	return yy_scan_bytes(yystr,strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (yyconst char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) yyalloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg )
{
    	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
        
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param line_number
 * 
 */
void yyset_lineno (int  line_number )
{
    
    yylineno = line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  in_str )
{
        yyin = in_str ;
}

void yyset_out (FILE *  out_str )
{
        yyout = out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  bdebug )
{
        yy_flex_debug = bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    /* We do not touch yylineno unless the option is enabled. */
    yylineno =  1;
    
    (yy_buffer_stack) = 0;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = (char *) 0;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = (FILE *) 0;
    yyout = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
	return (void *) malloc( size );
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void yyfree (void * ptr )
{
	free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 289 "new2.lex"



struct SymbolTable *table_head = NULL;
int table_size = 1;

int checkSymbol(char *current) {
  struct SymbolTable *curr_entry = table_head;
  while(curr_entry) {
    if(strcmp(curr_entry->content, current) == 0) {
      return curr_entry->index;
    }
    curr_entry = curr_entry->next;
  }
  return -1;
}


int insertSymbol(char *current) {
  int result = checkSymbol(current);
  if(result == -1) { 
    struct SymbolTable *new_entry = (struct SymbolTable *)malloc(sizeof(struct SymbolTable));
	table_size++;
    new_entry->index = table_size; 
    int size = strlen(current);
    new_entry->content = (char *)malloc((size+1)*sizeof(char));
    memcpy(new_entry->content, current, size+1);
    new_entry->next = table_head;
    table_head = new_entry;
    
    return new_entry->index;
  }
  else 
    return result;
}



int main(){
int token;

token=yylex();

while(token!=0){
	if(token==1){
		token=insertSymbol(yytext);
		/*epistrefei ti thesi sto pinaka symvolwn*/
		yylval.intval=token;
		printf("Symbol ID id :%d in Symbol Table\n",token);
	}
	token=yylex();

	}
return 0;

}

void ERROR(const char *msg){
	fprintf(stderr,"ERROR,at %d: %s\n",yylineno,msg);
	printf("%d: %s at %s in this line:\n%s\n",yylineno,msg, yytext, linebuf);
	exit(1);
	}





