// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2014.4
// Copyright (C) 2014 Xilinx Inc. All rights reserved.
// 
// ===========================================================

#include "array_io.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic array_io::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic array_io::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<6> array_io::ap_ST_st1_fsm_0 = "1";
const sc_lv<6> array_io::ap_ST_st2_fsm_1 = "10";
const sc_lv<6> array_io::ap_ST_st3_fsm_2 = "100";
const sc_lv<6> array_io::ap_ST_st4_fsm_3 = "1000";
const sc_lv<6> array_io::ap_ST_st5_fsm_4 = "10000";
const sc_lv<6> array_io::ap_ST_st6_fsm_5 = "100000";
const sc_lv<32> array_io::ap_const_lv32_0 = "00000000000000000000000000000000";
const sc_lv<1> array_io::ap_const_lv1_1 = "1";
const sc_lv<32> array_io::ap_const_lv32_1 = "1";
const sc_lv<1> array_io::ap_const_lv1_0 = "0";
const sc_lv<32> array_io::ap_const_lv32_3 = "11";
const sc_lv<32> array_io::ap_const_lv32_4 = "100";
const sc_lv<32> array_io::ap_const_lv32_5 = "101";
const sc_lv<20> array_io::ap_const_lv20_0 = "00000000000000000000";
const sc_lv<32> array_io::ap_const_lv32_2 = "10";
const sc_lv<5> array_io::ap_const_lv5_0 = "00000";
const sc_lv<9> array_io::ap_const_lv9_96 = "10010110";
const sc_lv<4> array_io::ap_const_lv4_1 = "1";
const sc_lv<64> array_io::ap_const_lv64_95 = "10010101";
const sc_lv<16> array_io::ap_const_lv16_1B = "11011";
const sc_lv<20> array_io::ap_const_lv20_BEC58 = "10111110110001011000";
const sc_lv<20> array_io::ap_const_lv20_1 = "1";
const sc_lv<5> array_io::ap_const_lv5_1B = "11011";
const sc_lv<5> array_io::ap_const_lv5_1 = "1";
const sc_lv<9> array_io::ap_const_lv9_8 = "1000";
const sc_lv<4> array_io::ap_const_lv4_9 = "1001";
const sc_lv<3> array_io::ap_const_lv3_0 = "000";
const sc_lv<16> array_io::ap_const_lv16_1 = "1";
const sc_lv<32> array_io::ap_const_lv32_F = "1111";
const sc_lv<9> array_io::ap_const_lv9_1 = "1";

array_io::array_io(sc_module_name name) : sc_module(name), mVcdFile(0) {

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_sig_cseq_ST_st4_fsm_3 );
    sensitive << ( exitcond1_fu_225_p2 );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_start );
    sensitive << ( ap_sig_cseq_ST_st1_fsm_0 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( ap_sig_cseq_ST_st4_fsm_3 );
    sensitive << ( exitcond1_fu_225_p2 );

    SC_METHOD(thread_ap_sig_bdd_102);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_bdd_117);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_bdd_22);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_bdd_55);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_bdd_72);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_bdd_88);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_cseq_ST_st1_fsm_0);
    sensitive << ( ap_sig_bdd_22 );

    SC_METHOD(thread_ap_sig_cseq_ST_st2_fsm_1);
    sensitive << ( ap_sig_bdd_55 );

    SC_METHOD(thread_ap_sig_cseq_ST_st3_fsm_2);
    sensitive << ( ap_sig_bdd_117 );

    SC_METHOD(thread_ap_sig_cseq_ST_st4_fsm_3);
    sensitive << ( ap_sig_bdd_72 );

    SC_METHOD(thread_ap_sig_cseq_ST_st5_fsm_4);
    sensitive << ( ap_sig_bdd_88 );

    SC_METHOD(thread_ap_sig_cseq_ST_st6_fsm_5);
    sensitive << ( ap_sig_bdd_102 );

    SC_METHOD(thread_d_i_address0);
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );
    sensitive << ( tmp_fu_220_p1 );
    sensitive << ( tmp_5_fu_254_p1 );
    sensitive << ( ap_sig_cseq_ST_st5_fsm_4 );

    SC_METHOD(thread_d_i_ce0);
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );
    sensitive << ( ap_sig_cseq_ST_st5_fsm_4 );

    SC_METHOD(thread_d_o_addr_3_gep_fu_134_p3);
    sensitive << ( tmp_5_reg_370 );
    sensitive << ( ap_sig_cseq_ST_st6_fsm_5 );
    sensitive << ( tmp_tmp_fu_287_p2 );
    sensitive << ( image_lsb_fu_259_p1 );

    SC_METHOD(thread_d_o_addr_4_gep_fu_142_p3);
    sensitive << ( tmp_5_reg_370 );
    sensitive << ( ap_sig_cseq_ST_st6_fsm_5 );
    sensitive << ( tmp_tmp_fu_287_p2 );
    sensitive << ( image_lsb_fu_259_p1 );

    SC_METHOD(thread_d_o_address0);
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );
    sensitive << ( tmp_reg_339 );
    sensitive << ( tmp_5_reg_370 );
    sensitive << ( ap_sig_cseq_ST_st6_fsm_5 );
    sensitive << ( ap_sig_cseq_ST_st3_fsm_2 );
    sensitive << ( tmp_tmp_fu_287_p2 );
    sensitive << ( d_o_addr_3_gep_fu_134_p3 );
    sensitive << ( image_lsb_fu_259_p1 );
    sensitive << ( d_o_addr_4_gep_fu_142_p3 );

    SC_METHOD(thread_d_o_ce0);
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );
    sensitive << ( ap_sig_cseq_ST_st6_fsm_5 );
    sensitive << ( ap_sig_cseq_ST_st3_fsm_2 );
    sensitive << ( tmp_tmp_fu_287_p2 );
    sensitive << ( image_lsb_fu_259_p1 );

    SC_METHOD(thread_d_o_d0);
    sensitive << ( d_i_q0 );
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );
    sensitive << ( ap_sig_cseq_ST_st6_fsm_5 );
    sensitive << ( ap_sig_cseq_ST_st3_fsm_2 );
    sensitive << ( tmp_tmp_fu_287_p2 );
    sensitive << ( image_lsb_fu_259_p1 );
    sensitive << ( tmp_2_fu_293_p2 );
    sensitive << ( tmp_4_fu_310_p3 );

    SC_METHOD(thread_d_o_we0);
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );
    sensitive << ( exitcond2_fu_208_p2 );
    sensitive << ( ap_sig_cseq_ST_st6_fsm_5 );
    sensitive << ( ap_sig_cseq_ST_st3_fsm_2 );
    sensitive << ( tmp_tmp_fu_287_p2 );
    sensitive << ( image_lsb_fu_259_p1 );

    SC_METHOD(thread_exitcond1_fu_225_p2);
    sensitive << ( ap_sig_cseq_ST_st4_fsm_3 );
    sensitive << ( i_1_reg_161 );

    SC_METHOD(thread_exitcond2_fu_208_p2);
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );
    sensitive << ( i_reg_150 );

    SC_METHOD(thread_exitcond_fu_248_p2);
    sensitive << ( ap_sig_cseq_ST_st5_fsm_4 );
    sensitive << ( j_reg_184 );

    SC_METHOD(thread_i_2_fu_214_p2);
    sensitive << ( i_reg_150 );

    SC_METHOD(thread_i_3_fu_231_p2);
    sensitive << ( i_1_reg_161 );

    SC_METHOD(thread_image_lsb_fu_259_p1);
    sensitive << ( d_i_q0 );

    SC_METHOD(thread_j_1_fu_325_p2);
    sensitive << ( j_reg_184 );

    SC_METHOD(thread_k_2_fu_237_p2);
    sensitive << ( k_reg_172 );

    SC_METHOD(thread_m_i_address0);
    sensitive << ( m_i_addr_reg_362 );
    sensitive << ( ap_sig_cseq_ST_st5_fsm_4 );

    SC_METHOD(thread_m_i_ce0);
    sensitive << ( ap_sig_cseq_ST_st5_fsm_4 );

    SC_METHOD(thread_message_bit_fu_283_p1);
    sensitive << ( tmp_9_fu_277_p2 );

    SC_METHOD(thread_tmp_10_fu_263_p1);
    sensitive << ( j_reg_184 );

    SC_METHOD(thread_tmp_1_fu_319_p2);
    sensitive << ( k_1_reg_196 );

    SC_METHOD(thread_tmp_2_fu_293_p2);
    sensitive << ( d_i_q0 );

    SC_METHOD(thread_tmp_3_fu_243_p1);
    sensitive << ( i_1_reg_161 );

    SC_METHOD(thread_tmp_4_fu_310_p3);
    sensitive << ( tmp_6_fu_300_p4 );

    SC_METHOD(thread_tmp_5_fu_254_p1);
    sensitive << ( k_1_reg_196 );

    SC_METHOD(thread_tmp_6_fu_300_p4);
    sensitive << ( d_i_q0 );

    SC_METHOD(thread_tmp_8_cast_fu_273_p1);
    sensitive << ( tmp_8_fu_267_p2 );

    SC_METHOD(thread_tmp_8_fu_267_p2);
    sensitive << ( tmp_10_fu_263_p1 );

    SC_METHOD(thread_tmp_9_fu_277_p2);
    sensitive << ( m_i_q0 );
    sensitive << ( tmp_8_cast_fu_273_p1 );

    SC_METHOD(thread_tmp_fu_220_p1);
    sensitive << ( i_reg_150 );

    SC_METHOD(thread_tmp_tmp_fu_287_p2);
    sensitive << ( image_lsb_fu_259_p1 );
    sensitive << ( message_bit_fu_283_p1 );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm );
    sensitive << ( exitcond2_fu_208_p2 );
    sensitive << ( exitcond1_fu_225_p2 );
    sensitive << ( exitcond_fu_248_p2 );

    SC_THREAD(thread_hdltv_gen);
    sensitive << ( ap_clk.pos() );

    ap_CS_fsm = "000001";
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "array_io_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, d_o_address0, "(port)d_o_address0");
    sc_trace(mVcdFile, d_o_ce0, "(port)d_o_ce0");
    sc_trace(mVcdFile, d_o_we0, "(port)d_o_we0");
    sc_trace(mVcdFile, d_o_d0, "(port)d_o_d0");
    sc_trace(mVcdFile, d_i_address0, "(port)d_i_address0");
    sc_trace(mVcdFile, d_i_ce0, "(port)d_i_ce0");
    sc_trace(mVcdFile, d_i_q0, "(port)d_i_q0");
    sc_trace(mVcdFile, m_i_address0, "(port)m_i_address0");
    sc_trace(mVcdFile, m_i_ce0, "(port)m_i_ce0");
    sc_trace(mVcdFile, m_i_q0, "(port)m_i_q0");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st1_fsm_0, "ap_sig_cseq_ST_st1_fsm_0");
    sc_trace(mVcdFile, ap_sig_bdd_22, "ap_sig_bdd_22");
    sc_trace(mVcdFile, i_2_fu_214_p2, "i_2_fu_214_p2");
    sc_trace(mVcdFile, i_2_reg_334, "i_2_reg_334");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st2_fsm_1, "ap_sig_cseq_ST_st2_fsm_1");
    sc_trace(mVcdFile, ap_sig_bdd_55, "ap_sig_bdd_55");
    sc_trace(mVcdFile, tmp_fu_220_p1, "tmp_fu_220_p1");
    sc_trace(mVcdFile, tmp_reg_339, "tmp_reg_339");
    sc_trace(mVcdFile, exitcond2_fu_208_p2, "exitcond2_fu_208_p2");
    sc_trace(mVcdFile, i_3_fu_231_p2, "i_3_fu_231_p2");
    sc_trace(mVcdFile, i_3_reg_352, "i_3_reg_352");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st4_fsm_3, "ap_sig_cseq_ST_st4_fsm_3");
    sc_trace(mVcdFile, ap_sig_bdd_72, "ap_sig_bdd_72");
    sc_trace(mVcdFile, k_2_fu_237_p2, "k_2_fu_237_p2");
    sc_trace(mVcdFile, k_2_reg_357, "k_2_reg_357");
    sc_trace(mVcdFile, exitcond1_fu_225_p2, "exitcond1_fu_225_p2");
    sc_trace(mVcdFile, m_i_addr_reg_362, "m_i_addr_reg_362");
    sc_trace(mVcdFile, tmp_5_fu_254_p1, "tmp_5_fu_254_p1");
    sc_trace(mVcdFile, tmp_5_reg_370, "tmp_5_reg_370");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st5_fsm_4, "ap_sig_cseq_ST_st5_fsm_4");
    sc_trace(mVcdFile, ap_sig_bdd_88, "ap_sig_bdd_88");
    sc_trace(mVcdFile, exitcond_fu_248_p2, "exitcond_fu_248_p2");
    sc_trace(mVcdFile, tmp_1_fu_319_p2, "tmp_1_fu_319_p2");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st6_fsm_5, "ap_sig_cseq_ST_st6_fsm_5");
    sc_trace(mVcdFile, ap_sig_bdd_102, "ap_sig_bdd_102");
    sc_trace(mVcdFile, j_1_fu_325_p2, "j_1_fu_325_p2");
    sc_trace(mVcdFile, i_reg_150, "i_reg_150");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st3_fsm_2, "ap_sig_cseq_ST_st3_fsm_2");
    sc_trace(mVcdFile, ap_sig_bdd_117, "ap_sig_bdd_117");
    sc_trace(mVcdFile, i_1_reg_161, "i_1_reg_161");
    sc_trace(mVcdFile, k_reg_172, "k_reg_172");
    sc_trace(mVcdFile, j_reg_184, "j_reg_184");
    sc_trace(mVcdFile, k_1_reg_196, "k_1_reg_196");
    sc_trace(mVcdFile, tmp_3_fu_243_p1, "tmp_3_fu_243_p1");
    sc_trace(mVcdFile, tmp_tmp_fu_287_p2, "tmp_tmp_fu_287_p2");
    sc_trace(mVcdFile, d_o_addr_3_gep_fu_134_p3, "d_o_addr_3_gep_fu_134_p3");
    sc_trace(mVcdFile, image_lsb_fu_259_p1, "image_lsb_fu_259_p1");
    sc_trace(mVcdFile, d_o_addr_4_gep_fu_142_p3, "d_o_addr_4_gep_fu_142_p3");
    sc_trace(mVcdFile, tmp_2_fu_293_p2, "tmp_2_fu_293_p2");
    sc_trace(mVcdFile, tmp_4_fu_310_p3, "tmp_4_fu_310_p3");
    sc_trace(mVcdFile, tmp_10_fu_263_p1, "tmp_10_fu_263_p1");
    sc_trace(mVcdFile, tmp_8_fu_267_p2, "tmp_8_fu_267_p2");
    sc_trace(mVcdFile, tmp_8_cast_fu_273_p1, "tmp_8_cast_fu_273_p1");
    sc_trace(mVcdFile, tmp_9_fu_277_p2, "tmp_9_fu_277_p2");
    sc_trace(mVcdFile, message_bit_fu_283_p1, "message_bit_fu_283_p1");
    sc_trace(mVcdFile, tmp_6_fu_300_p4, "tmp_6_fu_300_p4");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
#endif

    }
    mHdltvinHandle.open("array_io.hdltvin.dat");
    mHdltvoutHandle.open("array_io.hdltvout.dat");
}

array_io::~array_io() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    mHdltvinHandle << "] " << endl;
    mHdltvoutHandle << "] " << endl;
    mHdltvinHandle.close();
    mHdltvoutHandle.close();
}

void array_io::thread_ap_clk_no_reset_() {
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_st1_fsm_0;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st5_fsm_4.read()) && 
         !esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_fu_248_p2.read()))) {
        i_1_reg_161 = i_3_reg_352.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read()) && 
                !esl_seteq<1,1,1>(exitcond2_fu_208_p2.read(), ap_const_lv1_0))) {
        i_1_reg_161 = ap_const_lv5_0;
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st3_fsm_2.read())) {
        i_reg_150 = i_2_reg_334.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read()) && 
                !esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0))) {
        i_reg_150 = ap_const_lv20_0;
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st6_fsm_5.read())) {
        j_reg_184 = j_1_fu_325_p2.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st4_fsm_3.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_0, exitcond1_fu_225_p2.read()))) {
        j_reg_184 = ap_const_lv4_1;
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st6_fsm_5.read())) {
        k_1_reg_196 = tmp_1_fu_319_p2.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st4_fsm_3.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_0, exitcond1_fu_225_p2.read()))) {
        k_1_reg_196 = k_reg_172.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st5_fsm_4.read()) && 
         !esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_fu_248_p2.read()))) {
        k_reg_172 = k_2_reg_357.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read()) && 
                !esl_seteq<1,1,1>(exitcond2_fu_208_p2.read(), ap_const_lv1_0))) {
        k_reg_172 = ap_const_lv9_96;
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read())) {
        i_2_reg_334 = i_2_fu_214_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st4_fsm_3.read())) {
        i_3_reg_352 = i_3_fu_231_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st4_fsm_3.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, exitcond1_fu_225_p2.read()))) {
        k_2_reg_357 = k_2_fu_237_p2.read();
        m_i_addr_reg_362 =  (sc_lv<5>) (tmp_3_fu_243_p1.read());
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st5_fsm_4.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_fu_248_p2.read()))) {
        tmp_5_reg_370 = tmp_5_fu_254_p1.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read()) && esl_seteq<1,1,1>(exitcond2_fu_208_p2.read(), ap_const_lv1_0))) {
        tmp_reg_339 = tmp_fu_220_p1.read();
    }
}

void array_io::thread_ap_done() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st4_fsm_3.read()) && 
         !esl_seteq<1,1,1>(ap_const_lv1_0, exitcond1_fu_225_p2.read()))) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_const_logic_0;
    }
}

void array_io::thread_ap_idle() {
    if ((!esl_seteq<1,1,1>(ap_const_logic_1, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void array_io::thread_ap_ready() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st4_fsm_3.read()) && 
         !esl_seteq<1,1,1>(ap_const_lv1_0, exitcond1_fu_225_p2.read()))) {
        ap_ready = ap_const_logic_1;
    } else {
        ap_ready = ap_const_logic_0;
    }
}

void array_io::thread_ap_sig_bdd_102() {
    ap_sig_bdd_102 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(5, 5));
}

void array_io::thread_ap_sig_bdd_117() {
    ap_sig_bdd_117 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(2, 2));
}

void array_io::thread_ap_sig_bdd_22() {
    ap_sig_bdd_22 = esl_seteq<1,1,1>(ap_CS_fsm.read().range(0, 0), ap_const_lv1_1);
}

void array_io::thread_ap_sig_bdd_55() {
    ap_sig_bdd_55 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(1, 1));
}

void array_io::thread_ap_sig_bdd_72() {
    ap_sig_bdd_72 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(3, 3));
}

void array_io::thread_ap_sig_bdd_88() {
    ap_sig_bdd_88 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(4, 4));
}

void array_io::thread_ap_sig_cseq_ST_st1_fsm_0() {
    if (ap_sig_bdd_22.read()) {
        ap_sig_cseq_ST_st1_fsm_0 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st1_fsm_0 = ap_const_logic_0;
    }
}

void array_io::thread_ap_sig_cseq_ST_st2_fsm_1() {
    if (ap_sig_bdd_55.read()) {
        ap_sig_cseq_ST_st2_fsm_1 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st2_fsm_1 = ap_const_logic_0;
    }
}

void array_io::thread_ap_sig_cseq_ST_st3_fsm_2() {
    if (ap_sig_bdd_117.read()) {
        ap_sig_cseq_ST_st3_fsm_2 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st3_fsm_2 = ap_const_logic_0;
    }
}

void array_io::thread_ap_sig_cseq_ST_st4_fsm_3() {
    if (ap_sig_bdd_72.read()) {
        ap_sig_cseq_ST_st4_fsm_3 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st4_fsm_3 = ap_const_logic_0;
    }
}

void array_io::thread_ap_sig_cseq_ST_st5_fsm_4() {
    if (ap_sig_bdd_88.read()) {
        ap_sig_cseq_ST_st5_fsm_4 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st5_fsm_4 = ap_const_logic_0;
    }
}

void array_io::thread_ap_sig_cseq_ST_st6_fsm_5() {
    if (ap_sig_bdd_102.read()) {
        ap_sig_cseq_ST_st6_fsm_5 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st6_fsm_5 = ap_const_logic_0;
    }
}

void array_io::thread_d_i_address0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st5_fsm_4.read())) {
        d_i_address0 =  (sc_lv<20>) (tmp_5_fu_254_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read())) {
        d_i_address0 =  (sc_lv<20>) (tmp_fu_220_p1.read());
    } else {
        d_i_address0 = "XXXXXXXXXXXXXXXXXXXX";
    }
}

void array_io::thread_d_i_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st5_fsm_4.read()))) {
        d_i_ce0 = ap_const_logic_1;
    } else {
        d_i_ce0 = ap_const_logic_0;
    }
}

void array_io::thread_d_o_addr_3_gep_fu_134_p3() {
    d_o_addr_3_gep_fu_134_p3 =  (sc_lv<20>) (tmp_5_reg_370.read());
}

void array_io::thread_d_o_addr_4_gep_fu_142_p3() {
    d_o_addr_4_gep_fu_142_p3 =  (sc_lv<20>) (tmp_5_reg_370.read());
}

void array_io::thread_d_o_address0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st6_fsm_5.read()) && 
         !esl_seteq<1,1,1>(ap_const_lv1_0, tmp_tmp_fu_287_p2.read()) && 
         !esl_seteq<1,1,1>(ap_const_lv1_0, image_lsb_fu_259_p1.read()))) {
        d_o_address0 = d_o_addr_4_gep_fu_142_p3.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st6_fsm_5.read()) && 
                !esl_seteq<1,1,1>(ap_const_lv1_0, tmp_tmp_fu_287_p2.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_0, image_lsb_fu_259_p1.read()))) {
        d_o_address0 = d_o_addr_3_gep_fu_134_p3.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st6_fsm_5.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_0, tmp_tmp_fu_287_p2.read()))) {
        d_o_address0 =  (sc_lv<20>) (tmp_5_reg_370.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st3_fsm_2.read())) {
        d_o_address0 =  (sc_lv<20>) (tmp_reg_339.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read())) {
        d_o_address0 =  (sc_lv<20>) (ap_const_lv64_95);
    } else {
        d_o_address0 = "XXXXXXXXXXXXXXXXXXXX";
    }
}

void array_io::thread_d_o_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st3_fsm_2.read()) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st6_fsm_5.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, tmp_tmp_fu_287_p2.read())) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st6_fsm_5.read()) && 
          !esl_seteq<1,1,1>(ap_const_lv1_0, tmp_tmp_fu_287_p2.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, image_lsb_fu_259_p1.read())) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st6_fsm_5.read()) && 
          !esl_seteq<1,1,1>(ap_const_lv1_0, tmp_tmp_fu_287_p2.read()) && 
          !esl_seteq<1,1,1>(ap_const_lv1_0, image_lsb_fu_259_p1.read())))) {
        d_o_ce0 = ap_const_logic_1;
    } else {
        d_o_ce0 = ap_const_logic_0;
    }
}

void array_io::thread_d_o_d0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st6_fsm_5.read()) && 
         !esl_seteq<1,1,1>(ap_const_lv1_0, tmp_tmp_fu_287_p2.read()) && 
         !esl_seteq<1,1,1>(ap_const_lv1_0, image_lsb_fu_259_p1.read()))) {
        d_o_d0 = tmp_4_fu_310_p3.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st6_fsm_5.read()) && 
                !esl_seteq<1,1,1>(ap_const_lv1_0, tmp_tmp_fu_287_p2.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_0, image_lsb_fu_259_p1.read()))) {
        d_o_d0 = tmp_2_fu_293_p2.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st3_fsm_2.read()) || 
                (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st6_fsm_5.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_0, tmp_tmp_fu_287_p2.read())))) {
        d_o_d0 = d_i_q0.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read())) {
        d_o_d0 = ap_const_lv16_1B;
    } else {
        d_o_d0 =  (sc_lv<16>) ("XXXXXXXXXXXXXXXX");
    }
}

void array_io::thread_d_o_we0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st3_fsm_2.read()) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read()) && 
          !esl_seteq<1,1,1>(exitcond2_fu_208_p2.read(), ap_const_lv1_0)) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st6_fsm_5.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, tmp_tmp_fu_287_p2.read())) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st6_fsm_5.read()) && 
          !esl_seteq<1,1,1>(ap_const_lv1_0, tmp_tmp_fu_287_p2.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, image_lsb_fu_259_p1.read())) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st6_fsm_5.read()) && 
          !esl_seteq<1,1,1>(ap_const_lv1_0, tmp_tmp_fu_287_p2.read()) && 
          !esl_seteq<1,1,1>(ap_const_lv1_0, image_lsb_fu_259_p1.read())))) {
        d_o_we0 = ap_const_logic_1;
    } else {
        d_o_we0 = ap_const_logic_0;
    }
}

void array_io::thread_exitcond1_fu_225_p2() {
    exitcond1_fu_225_p2 = (!i_1_reg_161.read().is_01() || !ap_const_lv5_1B.is_01())? sc_lv<1>(): sc_lv<1>(i_1_reg_161.read() == ap_const_lv5_1B);
}

void array_io::thread_exitcond2_fu_208_p2() {
    exitcond2_fu_208_p2 = (!i_reg_150.read().is_01() || !ap_const_lv20_BEC58.is_01())? sc_lv<1>(): sc_lv<1>(i_reg_150.read() == ap_const_lv20_BEC58);
}

void array_io::thread_exitcond_fu_248_p2() {
    exitcond_fu_248_p2 = (!j_reg_184.read().is_01() || !ap_const_lv4_9.is_01())? sc_lv<1>(): sc_lv<1>(j_reg_184.read() == ap_const_lv4_9);
}

void array_io::thread_i_2_fu_214_p2() {
    i_2_fu_214_p2 = (!i_reg_150.read().is_01() || !ap_const_lv20_1.is_01())? sc_lv<20>(): (sc_biguint<20>(i_reg_150.read()) + sc_biguint<20>(ap_const_lv20_1));
}

void array_io::thread_i_3_fu_231_p2() {
    i_3_fu_231_p2 = (!i_1_reg_161.read().is_01() || !ap_const_lv5_1.is_01())? sc_lv<5>(): (sc_biguint<5>(i_1_reg_161.read()) + sc_biguint<5>(ap_const_lv5_1));
}

void array_io::thread_image_lsb_fu_259_p1() {
    image_lsb_fu_259_p1 = d_i_q0.read().range(1-1, 0);
}

void array_io::thread_j_1_fu_325_p2() {
    j_1_fu_325_p2 = (!j_reg_184.read().is_01() || !ap_const_lv4_1.is_01())? sc_lv<4>(): (sc_biguint<4>(j_reg_184.read()) + sc_biguint<4>(ap_const_lv4_1));
}

void array_io::thread_k_2_fu_237_p2() {
    k_2_fu_237_p2 = (!k_reg_172.read().is_01() || !ap_const_lv9_8.is_01())? sc_lv<9>(): (sc_biguint<9>(k_reg_172.read()) + sc_biguint<9>(ap_const_lv9_8));
}

void array_io::thread_m_i_address0() {
    m_i_address0 = m_i_addr_reg_362.read();
}

void array_io::thread_m_i_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st5_fsm_4.read())) {
        m_i_ce0 = ap_const_logic_1;
    } else {
        m_i_ce0 = ap_const_logic_0;
    }
}

void array_io::thread_message_bit_fu_283_p1() {
    message_bit_fu_283_p1 = tmp_9_fu_277_p2.read().range(1-1, 0);
}

void array_io::thread_tmp_10_fu_263_p1() {
    tmp_10_fu_263_p1 = j_reg_184.read().range(3-1, 0);
}

void array_io::thread_tmp_1_fu_319_p2() {
    tmp_1_fu_319_p2 = (!k_1_reg_196.read().is_01() || !ap_const_lv9_1.is_01())? sc_lv<9>(): (sc_biguint<9>(k_1_reg_196.read()) + sc_biguint<9>(ap_const_lv9_1));
}

void array_io::thread_tmp_2_fu_293_p2() {
    tmp_2_fu_293_p2 = (d_i_q0.read() | ap_const_lv16_1);
}

void array_io::thread_tmp_3_fu_243_p1() {
    tmp_3_fu_243_p1 = esl_zext<64,5>(i_1_reg_161.read());
}

void array_io::thread_tmp_4_fu_310_p3() {
    tmp_4_fu_310_p3 = esl_concat<15,1>(tmp_6_fu_300_p4.read(), ap_const_lv1_0);
}

void array_io::thread_tmp_5_fu_254_p1() {
    tmp_5_fu_254_p1 = esl_zext<64,9>(k_1_reg_196.read());
}

void array_io::thread_tmp_6_fu_300_p4() {
    tmp_6_fu_300_p4 = d_i_q0.read().range(15, 1);
}

void array_io::thread_tmp_8_cast_fu_273_p1() {
    tmp_8_cast_fu_273_p1 = esl_zext<16,3>(tmp_8_fu_267_p2.read());
}

void array_io::thread_tmp_8_fu_267_p2() {
    tmp_8_fu_267_p2 = (!ap_const_lv3_0.is_01() || !tmp_10_fu_263_p1.read().is_01())? sc_lv<3>(): (sc_biguint<3>(ap_const_lv3_0) - sc_biguint<3>(tmp_10_fu_263_p1.read()));
}

void array_io::thread_tmp_9_fu_277_p2() {
    tmp_9_fu_277_p2 = (!m_i_q0.read().is_01() || !tmp_8_cast_fu_273_p1.read().is_01())? sc_lv<16>(): sc_bigint<16>(m_i_q0.read()) >> (unsigned short)tmp_8_cast_fu_273_p1.read().to_uint();
}

void array_io::thread_tmp_fu_220_p1() {
    tmp_fu_220_p1 = esl_zext<64,20>(i_reg_150.read());
}

void array_io::thread_tmp_tmp_fu_287_p2() {
    tmp_tmp_fu_287_p2 = (image_lsb_fu_259_p1.read() ^ message_bit_fu_283_p1.read());
}

void array_io::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            if (!esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0)) {
                ap_NS_fsm = ap_ST_st2_fsm_1;
            } else {
                ap_NS_fsm = ap_ST_st1_fsm_0;
            }
            break;
        case 2 : 
            if (!esl_seteq<1,1,1>(exitcond2_fu_208_p2.read(), ap_const_lv1_0)) {
                ap_NS_fsm = ap_ST_st4_fsm_3;
            } else {
                ap_NS_fsm = ap_ST_st3_fsm_2;
            }
            break;
        case 4 : 
            ap_NS_fsm = ap_ST_st2_fsm_1;
            break;
        case 8 : 
            if (!esl_seteq<1,1,1>(ap_const_lv1_0, exitcond1_fu_225_p2.read())) {
                ap_NS_fsm = ap_ST_st1_fsm_0;
            } else {
                ap_NS_fsm = ap_ST_st5_fsm_4;
            }
            break;
        case 16 : 
            if (!esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_fu_248_p2.read())) {
                ap_NS_fsm = ap_ST_st4_fsm_3;
            } else {
                ap_NS_fsm = ap_ST_st6_fsm_5;
            }
            break;
        case 32 : 
            ap_NS_fsm = ap_ST_st5_fsm_4;
            break;
        default : 
            ap_NS_fsm =  (sc_lv<6>) ("XXXXXX");
            break;
    }
}

void array_io::thread_hdltv_gen() {
    const char* dump_tv = std::getenv("AP_WRITE_TV");
    if (!(dump_tv && string(dump_tv) == "on")) return;

    wait();

    mHdltvinHandle << "[ " << endl;
    mHdltvoutHandle << "[ " << endl;
    int ap_cycleNo = 0;
    while (1) {
        wait();
        const char* mComma = ap_cycleNo == 0 ? " " : ", " ;
        mHdltvinHandle << mComma << "{"  <<  " \"ap_rst\" :  \"" << ap_rst.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"ap_start\" :  \"" << ap_start.read() << "\" ";
        mHdltvoutHandle << mComma << "{"  <<  " \"ap_done\" :  \"" << ap_done.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"ap_idle\" :  \"" << ap_idle.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"ap_ready\" :  \"" << ap_ready.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"d_o_address0\" :  \"" << d_o_address0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"d_o_ce0\" :  \"" << d_o_ce0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"d_o_we0\" :  \"" << d_o_we0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"d_o_d0\" :  \"" << d_o_d0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"d_i_address0\" :  \"" << d_i_address0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"d_i_ce0\" :  \"" << d_i_ce0.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"d_i_q0\" :  \"" << d_i_q0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"m_i_address0\" :  \"" << m_i_address0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"m_i_ce0\" :  \"" << m_i_ce0.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"m_i_q0\" :  \"" << m_i_q0.read() << "\" ";
        mHdltvinHandle << "}" << std::endl;
        mHdltvoutHandle << "}" << std::endl;
        ap_cycleNo++;
    }
}

}

